from pathlib import Path

# Fix the compact desktop money-action surface generated by the refactor script.
p = Path('lib/features/account/account_page.dart')
text = p.read_text()
old = """        child: Ink(
          height: 28,
          alignment: Alignment.center,
          padding: const EdgeInsets.symmetric(horizontal: 4),
          decoration: BoxDecoration(
            color: c.primarySoft,
            borderRadius: BorderRadius.circular(AppRadius.sm),
            border: Border.all(color: c.primary.withValues(alpha: 0.16)),
          ),
          child: Text(
            label,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
            style: AppTextStyles.caption.copyWith(
              color: c.primary,
              fontSize: 10,
              fontWeight: FontWeight.w800,
            ),
          ),
        ),
"""
new = """        child: Ink(
          height: 28,
          padding: const EdgeInsets.symmetric(horizontal: 4),
          decoration: BoxDecoration(
            color: c.primarySoft,
            borderRadius: BorderRadius.circular(AppRadius.sm),
            border: Border.all(color: c.primary.withValues(alpha: 0.16)),
          ),
          child: Center(
            child: Text(
              label,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: AppTextStyles.caption.copyWith(
                color: c.primary,
                fontSize: 10,
                fontWeight: FontWeight.w800,
              ),
            ),
          ),
        ),
"""
if old not in text:
    raise SystemExit('desktop money action anchor not found')
p.write_text(text.replace(old, new, 1))

# Guard the exact BuildContext used after async recharge-order creation.
p = Path('lib/features/account/wallet_page.dart')
text = p.read_text()
old = """    final ctrl = AppScope.of(context);
    final dialogContext = Navigator.of(context, rootNavigator: true).context;
    setState(() => _submitting = true);
    try {
      final tradeNo = await ctrl.api.submitRechargeOrder(
        (amount * 100).round(),
      );
      if (!mounted) return;
      Navigator.of(context).pop();
      await showOrderPaymentDialog(
        context: dialogContext,
        tradeNo: tradeNo,
        finalPrice: amount,
        api: ctrl.api,
        currencySymbol: ctrl.currencySymbol,
      );
      await ctrl.refreshData();
    } catch (e) {
      if (dialogContext.mounted) {
        AppToast.show(
          dialogContext,
          e.toString().replaceFirst('ApiException: ', ''),
          type: AppToastType.error,
        );
      }
"""
new = """    final ctrl = AppScope.of(context);
    final navigator = Navigator.of(context);
    final dialogContext = Navigator.of(context, rootNavigator: true).context;
    setState(() => _submitting = true);
    try {
      final tradeNo = await ctrl.api.submitRechargeOrder(
        (amount * 100).round(),
      );
      if (!mounted || !dialogContext.mounted) return;
      navigator.pop();
      await showOrderPaymentDialog(
        context: dialogContext,
        tradeNo: tradeNo,
        finalPrice: amount,
        api: ctrl.api,
        currencySymbol: ctrl.currencySymbol,
      );
      await ctrl.refreshData();
    } catch (e) {
      if (dialogContext.mounted) {
        AppToast.show(
          dialogContext,
          e.toString().replaceFirst('ApiException: ', ''),
          type: AppToastType.error,
        );
      }
"""
if old not in text:
    raise SystemExit('recharge async context anchor not found')
p.write_text(text.replace(old, new, 1))
