import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:cryptography/cryptography.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:shared_preferences/shared_preferences.dart';

import '../shared/config/app_config.dart';
import '../shared/services/secure_logger.dart';

/// Fetches brand/API config from OSS and applies it to [AppConfig].
///
/// Startup order:
/// 1. trusted local cache from the previous successful OSS refresh
/// 2. bundled build-time config generated by tool/apply_branding.dart
/// 3. compiled AppConfig defaults
/// 4. background OSS refresh for the next/current session
abstract final class RemoteConfigService {
  // ── Editable settings ─────────────────────────────────────────────────────

  /// OSS URL for the remote config wrapper or legacy JSON config.
  static const configUrl = 'https://oss.litchi.cfd/config.json';

  /// Build-time fallback config. The white-label build script writes the same
  /// remote config payload/wrapper here before `flutter build`, so first-launch
  /// users can still get the correct API domains and layout when OSS is blocked.
  /// This file lives under assets/images because pubspec already includes that
  /// whole directory.
  static const bundledConfigAsset =
      'assets/images/default_remote_config.json';

  /// Ed25519 public key, encoded with base64url without padding.
  ///
  /// Generate once with:
  ///   dart run tool/sign_remote_config.dart generate
  ///
  /// Put PUBLIC_KEY here. Keep PRIVATE_KEY offline and never commit it.
  /// While this is left as the placeholder value, unsigned legacy config is
  /// still accepted for rollout compatibility.
  static const publicKeyBase64Url =
      'J9E-BBh19QQsGhpAJd654FkxN09pcH2K4FMq_3lYEyw';

  // ── Internal settings ─────────────────────────────────────────────────────

  static const _cacheKey = 'remote_config_v1';
  static const _highestVersionKey = 'remote_config_highest_version_v1';
  static const _timeout = Duration(seconds: 5);

  static bool get _requiresSignature =>
      publicKeyBase64Url.isNotEmpty &&
      !publicKeyBase64Url.startsWith('REPLACE_WITH_');

  /// Call once in main(), before runApp().
  ///
  /// Applies cached config immediately (if any). On first launch with no cache,
  /// applies the bundled build-time config before trying OSS, so API bases,
  /// branding and custom layout are available even when the config domain is
  /// unreachable.
  static Future<void> initialize(SharedPreferences prefs) async {
    final applied = await _applyCached(prefs) || await _applyBundled(prefs);

    if (applied) {
      unawaited(_refresh(prefs));
    } else {
      // First launch with no cache and no bundled config: await a bounded first
      // fetch so API base has a chance to be ready before login/API setup.
      await _refresh(prefs);
    }
  }

  static Future<bool> _applyCached(SharedPreferences prefs) async {
    final cached = prefs.getString(_cacheKey);
    if (cached == null || cached.isEmpty) return false;
    try {
      final config = await _parseTrustedConfig(cached);
      if (config != null && await _acceptConfig(config, prefs)) {
        AppConfig.applyRemote(config);
        return true;
      }
    } catch (e) {
      SecureLogger.warn('RemoteConfig cached config rejected', e);
    }
    return false;
  }

  static Future<bool> _applyBundled(SharedPreferences prefs) async {
    try {
      final body = await rootBundle.loadString(bundledConfigAsset);
      final config = await _parseBundledConfig(body);
      if (config == null || !await _acceptConfig(config, prefs)) return false;
      AppConfig.applyRemote(config);
      return true;
    } catch (_) {
      // Missing bundled config is fine for development/default builds.
      return false;
    }
  }

  static Future<void> _refresh(SharedPreferences prefs) async {
    HttpClient? client;
    try {
      client = HttpClient()..connectionTimeout = _timeout;
      final request = await client
          .getUrl(Uri.parse(configUrl))
          .timeout(_timeout);
      request.headers.set('Accept', 'application/json');

      final response = await request.close().timeout(_timeout);
      if (response.statusCode != 200) return;

      final body = await response
          .transform(const Utf8Decoder())
          .join()
          .timeout(_timeout);

      final config = await _parseTrustedConfig(body);
      if (config == null) return;
      if (!await _acceptConfig(config, prefs)) return;

      // Persist the original trusted body for next launch. For signed config,
      // this keeps the signature wrapper so cache is re-verified on every start.
      await prefs.setString(_cacheKey, body);

      // Also apply to current session (colors/text update live if widgets rebuild).
      AppConfig.applyRemote(config);
    } catch (e) {
      // Network unavailable, JSON malformed, or signature invalid — non-fatal,
      // but record it so a persistently broken remote config is diagnosable.
      SecureLogger.warn('RemoteConfig refresh failed', e);
    } finally {
      client?.close(force: true);
    }
  }

  /// Parses a legacy config or a signed wrapper from network/cache.
  ///
  /// Signed format:
  /// {
  ///   "payload_b64": "base64url(utf8(jsonPayload))",
  ///   "signature": "base64url(ed25519_signature(payload_bytes))"
  /// }
  static Future<Map<String, dynamic>?> _parseTrustedConfig(String body) async {
    final decoded = jsonDecode(body);
    if (decoded is! Map<String, dynamic>) return null;

    if (_looksSigned(decoded)) {
      return _verifySigned(decoded);
    }

    if (_requiresSignature) return null;
    return decoded;
  }

  /// Parses the config bundled into the app by the build script.
  ///
  /// A signed wrapper is verified. A plain payload is also accepted because it is
  /// part of the compiled application package and is only used as first-launch
  /// fallback when no remote cache exists.
  static Future<Map<String, dynamic>?> _parseBundledConfig(String body) async {
    final decoded = jsonDecode(body);
    if (decoded is! Map<String, dynamic>) return null;

    if (_looksSigned(decoded)) {
      return _verifySigned(decoded);
    }

    return decoded;
  }

  static bool _looksSigned(Map<String, dynamic> json) =>
      json['payload_b64'] is String && json['signature'] is String;

  static Future<Map<String, dynamic>?> _verifySigned(
    Map<String, dynamic> wrapper,
  ) async {
    if (!_requiresSignature) return null;

    try {
      final payloadB64 = wrapper['payload_b64'] as String;
      final signatureB64 = wrapper['signature'] as String;
      final payloadBytes = _base64UrlDecode(payloadB64);
      final signatureBytes = _base64UrlDecode(signatureB64);
      final publicKeyBytes = _base64UrlDecode(publicKeyBase64Url);

      final algorithm = Ed25519();
      final publicKey = SimplePublicKey(
        publicKeyBytes,
        type: KeyPairType.ed25519,
      );
      final signature = Signature(signatureBytes, publicKey: publicKey);
      final ok = await algorithm.verify(payloadBytes, signature: signature);
      if (!ok) return null;

      final payload = jsonDecode(utf8.decode(payloadBytes));
      if (payload is! Map<String, dynamic>) return null;
      return payload;
    } catch (_) {
      return null;
    }
  }

  static Future<bool> _acceptConfig(
    Map<String, dynamic> config,
    SharedPreferences prefs,
  ) async {
    if (!_requiresSignature) return true;

    final version = _configVersion(config['config_version']);
    final expiresAt = _expiresAt(config['expires_at']);
    if (version == null || expiresAt == null) {
      SecureLogger.warn('RemoteConfig rejected: missing version/expiry');
      return false;
    }
    if (!DateTime.now().toUtc().isBefore(expiresAt)) {
      SecureLogger.warn('RemoteConfig rejected: expired');
      return false;
    }

    final highest = prefs.getInt(_highestVersionKey) ?? 0;
    if (version < highest) {
      SecureLogger.warn('RemoteConfig rejected: rollback $version < $highest');
      return false;
    }
    if (version > highest) {
      await prefs.setInt(_highestVersionKey, version);
    }
    return true;
  }

  static int? _configVersion(Object? value) {
    if (value is int && value > 0) return value;
    if (value is num && value > 0) return value.toInt();
    if (value is String) {
      final parsed = int.tryParse(value.trim());
      if (parsed != null && parsed > 0) return parsed;
    }
    return null;
  }

  static DateTime? _expiresAt(Object? value) {
    if (value is int) {
      return DateTime.fromMillisecondsSinceEpoch(value * 1000, isUtc: true);
    }
    if (value is num) {
      return DateTime.fromMillisecondsSinceEpoch(
        value.toInt() * 1000,
        isUtc: true,
      );
    }
    if (value is String) {
      final trimmed = value.trim();
      final epoch = int.tryParse(trimmed);
      if (epoch != null) {
        return DateTime.fromMillisecondsSinceEpoch(epoch * 1000, isUtc: true);
      }
      return DateTime.tryParse(trimmed)?.toUtc();
    }
    return null;
  }

  static List<int> _base64UrlDecode(String raw) {
    final normalized = raw.trim().replaceAll('-', '+').replaceAll('_', '/');
    final padded = normalized.padRight(
      normalized.length + ((4 - normalized.length % 4) % 4),
      '=',
    );
    return base64.decode(padded);
  }
}
