-keep class io.flutter.** { *; }
-dontwarn io.flutter.**

# libbox is generated by gomobile and exposes Java-visible classes and callbacks.
-keep class io.nekohasekai.libbox.** { *; }
-dontwarn io.nekohasekai.libbox.**
-keep class com.litchi.client.AndroidSingBoxEngine { *; }
-keep class com.litchi.client.AndroidSingBoxPlatform { *; }
-keep class com.litchi.client.LitchiVpnService { *; }
-keep class com.litchi.client.LitchiCoreService { *; }

-keepattributes *Annotation*
-keep class kotlin.** { *; }
-dontwarn kotlin.**
-dontwarn okhttp3.**
-dontwarn okio.**
